### ISSUE TITLE
vocab size

### ISSUE THREAD

**Issue by haorannlp** [ictnlp/OR-NMT#3]
Hi, Zhang Wen!
When I apply BPE using command `subword-nmt learn-joint-bpe-and-vocab --input train.en train.de -s 37000 -o bpe_code.en.de --write-vocabulary en.vocab de.vocab`,  the vocab sizes of ENG, DE are 39320, 40364, respectively (In your paper, they are 39418, 40274). Did I miss something here? Besides, does 'tgru' mean 2 GRU cells? Any help would be greatly appreciated.

**Comment by zhang-wen** [comment]
@haorannlp Hi, I think this is reasonable, because we may not filter the training set in the same way, so the number of sentence pairs in the training set may not be the same. Anyway, differences in vocabulary size will not have a big effect.  No, tgru means the model proposed in the paper "DTMT: A Novel Deep Transition Architecture for Neural Machine Translation", please refer to this paper for more details.

**Comment by haorannlp** [comment]
Thank you
